services:
  articles-sync:
    # Dev override: build locally instead of pulling GHCR image.
    build:
      context: ./articles-sync
      dockerfile: Dockerfile

  web-app:
    # Dev override: build locally instead of pulling GHCR image.
    build:
      context: ./web-app
      dockerfile: Dockerfile
    volumes:
      - ./web-app:/app
      - rendered_html_articles:/articles/rendered
      - source_md_articles:/articles/src:ro
    environment:
      - APP_ENV=development
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=sqlite:///project_test.db
    command: ["flask", "run", "--host=0.0.0.0", "--debug"]

  nginx-modsecurity:
    volumes:
      - ./nginx-modsecurity/conf.d/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - rendered_html_articles:/usr/share/nginx/html/rendered-articles
